### ISSUE TITLE
Server crashes when trying to login - "Can't reconnect until invalid transaction is rolled back"

### ISSUE THREAD

**Issue by zelima** [datahq/auth#11]
While ago, was registered and able to push files to datahub. Apr ~15 hours later tried to run `data login` and getting 
```
invalid json response body at http://api-testing.datahub.io/auth/check?jwt=HereGoesToken&next=http://localhost:3000 reason: Unexpected token < in JSON at position 0
```

Checking the Auth logs we have problem with connecting to database - SQLalchemy invalidRequestError

```
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
```

Not sure, but this might be related to reusing session -  according to this https://stackoverflow.com/a/42396447 it happens when using session while SQLachemy error is raised

**Comment by akariv** [comment]
I will handle this - saw the same problem with specstore so basically just
need to copy the solution from there.

**Comment by akariv** [comment]
Fixed in https://github.com/datahq/auth/commits/e3459c6
