### ISSUE TITLE
Get guaranteed emails from github

### ISSUE THREAD

**Issue by zelima** [datahq/auth#2]
Currently, we are getting nulls from GitHub API if the user has a  submitted email to be private.

Reason and solution for this is in http://stackoverflow.com/questions/35373995/github-user-email-is-null-despite-useremail-scope

To get private emails we need to call: `GET https://api.github.com/user/emails`

## Acceptance criteria

* [x] We have emails even if they are private on GitHub

## Tasks

* [x] write tests 
* [x] add the check to script and make separate API call

**Comment by rufuspollock** [comment]
@zelima is this fixed - if so can you close.

**Comment by zelima** [comment]
FIXED
